# Generated by Django 3.2.9 on 2021-12-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messaging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageThreadModel',
        ),
    ]
