# Generated by Django 3.2.9 on 2021-12-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messaging', '0002_delete_messagethreadmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='sender_user',
            new_name='sender',
        ),
    ]
